image:
  tag: "v3.0.0-beta3"

ingressClass:
  enabled: true
  isDefaultClass: false

providers:
  kubernetesIngress:
    enabled: true
    namespaces: []
    ingressClass: traefik

service:
  enabled: true
  type: NodePort 

# Configure ports
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  metrics:
    port: 9100
      
metrics:
  prometheus:
    entryPoint: metrics

tracing:
  jaeger:
    localAgentHostPort: otel-demo-otelcol.default.svc.cluster.local:6831

 #metrics:
 #  openTelemetry:
 #    address: otelcol.default.svc.cluster.local:4318
 #    insecure: true
 #
 #tracing:
 #  openTelemetry:
 #    address: otelcol.default.svc.cluster.local:4318
 #    insecure: true
