ingressClass:
  enabled: true
  isDefaultClass: false

providers:
  kubernetesIngress:
    enabled: true
    namespaces: []
    ingressClass: traefik

# Configure ports
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443

tls:
  certificates:
    - certFile: /home/u/kind/kind-traefik-ingress/_wildcard.192.168.56.101.nip.io+4.pem
      keyFile: /home/u/kind/kind-traefik-ingress/_wildcard.192.168.56.101.nip.io+4-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /home/u/kind/kind-traefik-ingress/_wildcard.192.168.56.101.nip.io+4.pem
        keyFile: /home/u/kind/kind-traefik-ingress/_wildcard.192.168.56.101.nip.io+4-key.pem
        
