image:
  tag: "v3.1.5"

ingressClass:
  enabled: true
  isDefaultClass: false

providers:
  kubernetesIngress:
    enabled: true
    namespaces: []
    ingressClass: traefik

service:
  enabled: true
  type: NodePort 

# Configure ports
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
  metrics:
    port: 9100

#additional traefik static config. CLI 
#https://docs.traefik.io/reference/static-configuration/cli/
# allow local selfsign certs for dev
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  
  
# #metrics:
# #  prometheus:
# #    entryPoint: metrics
# #
# #tracing:
# #  jaeger:
# #    localAgentHostPort: otel-demo-otelcol.default.svc.cluster.local:6831

# metrics:
#   openTelemetry:
#     address: my-opentelemetry-collector.default.svc.cluster.local:4318
#     insecure: true

# tracing:
#   openTelemetry:
#     address: my-opentelemetry-collector.default.svc.cluster.local:4318
#     insecure: true
